TravelBuddy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.travel.urls', namespace='travel')),
    url(r'^LogReg/', include('apps.LogReg.urls', namespace="logreg")),
]

apps/LogReg/urls.py
#LogReg
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register$', views.log_reg, name="register"),
    url(r'^login$', views.log_reg, name="login"),
    url(r'^logout$', views.logout, name="logout"),
]

#if we have the same views.method do we use the same name?
#what is the difference between using a regex with the $ at the end and not?

apps/travel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name="main"),
    url(r'^travels$', views.dashboard, name="dashboard"),
    url(r'^travels/destination/(?P<id>\d+)/$', views.destination, name="destination"),
    url(r'^travels/add$', views.add_page, name='add_page'),
    url(r'^travels/add/trip', views.add, name="add"),
    url(r'^travels/join/(?P<id>\d+)/$', views.join, name='join'),
]

apps/LogReg/models.py
#LogReg
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import bcrypt, re

#regex for name that has spaces in it
NAMEREG = re.compile(r'^[a-zA-Z.-]+( [a-zA-Z.-]+)*$')

class userDBManager(models.Manager):
    def check_create(self, data):
        errors = []
        if len(data['name']) < 3:
            errors.append(['name', "Name must be at least three characters in length."])
        if len(data['username']) < 3:
            errors.append(['name', "Username must be at least three characters in length."])
        if not re.match(NAMEREG, data['name']) or not re.match(NAMEREG, data['username']):
            errors.append(['name', 'Name and username must only include letters and "-" or "." please.'])
        if len(data['password']) < 8:
            errors.append(['password', 'Password must be at least 8 characters.'])
        if len(data['password_confirmation']) < 8 or data['password_confirmation'] != data['password']:
            errors.append(['password_confirmation', 'Password confirmation must be entered and match password.'])
        if errors:
            return [False, errors]
        else:
            user_check = userDB.objects.filter(username=data['username'])
            if user_check:
                errors.append(['user_check', 'Unable to register, please use alternate information.'])
                return [False, errors]
            newUser = userDB(name=data['name'], username=data['username'])
            hashed_pass = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            newUser.password = hashed_pass
            newUser.save()
            return [True, newUser]

    def check_login(self, data):
        errors = []
        if len(data['username']) < 3:
            errors.append(['name', "Username must be at least three characters in length."])
        if len(data['password']) < 8:
            errors.append(['password', 'Password must be at least 8 characters.'])
        if errors:
            return [False, errors]
        else:
            check_user = userDB.objects.filter(username=data['username'])
            if not check_user:
                errors.append(['login', "Username or password not correct.  Please try again."])
            if not bcrypt.checkpw(data['password'].encode(), check_user[0].password.encode()):
                errors.append(['login', "Email or password not correct.  Please try again."])
            if errors:
                return [False, errors]
            else:
                user = check_user[0]
                print user
                return [True, user]




class userDB(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return 'ID: %s | Name: %s | Username %s' % (self.id, self.name, self.username)
    objects = userDBManager()
# Create your models here.

apps/travel/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from ..LogReg.models import userDB
from datetime import datetime

class TripManager(models.Manager):
    def check_trip(self, data, user):
        errors = []
        today = datetime.now().date()
        start = datetime.strptime(data['travel_start_date'], '%Y-%m-%d').date()
        end = datetime.strptime(data['travel_end_date'], '%Y-%m-%d').date()
        if len(data['destination']) < 1 or len(data['plan']) < 1 or len(data['travel_start_date']) < 1 or len(data['travel_end_date']) < 1:
            errors.append(['destination and plan', 'All fields must be entered.'])
        #validate dates are future
        if start < today or end < today:
            errors.append(['date', 'Traveling dates must be in the future.'])
        # #validate date to not before date from
        if end < start:
            errors.append(['date', 'End date must be later than start date.'])

        if errors:
            return [False, errors]
        else:
            newTrip = Trip.objects.create(destination=data['destination'], plan=data['plan'], planner=user, travel_start_date=data['travel_start_date'],  travel_end_date=data['travel_end_date'])
            newTrip.travelers.add(user)
            newTrip.save()
            return [True]
# Create your models here.
class Trip(models.Model):
    destination = models.CharField(max_length=100)
    plan = models.TextField()
    planner = models.ForeignKey(userDB, related_name='trip_planner')
    travelers = models.ManyToManyField(userDB, related_name='trip_travelers')
    travel_start_date = models.DateTimeField()
    travel_end_date = models.DateTimeField()
    objects = TripManager()

apps/LogReg/views.py
#LogReg
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import userDB

# Create your views here.

def log_reg(request):
    if request.method == "POST":
        if request.POST['attempt'] == "register":
            response = userDB.objects.check_create(request.POST)
        elif request.POST['attempt'] == 'login':
            response = userDB.objects.check_login(request.POST)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
            return redirect('travel:main')
        else:
            request.session['user'] = {
                'name': response[1].name,
                'username' : response[1].username,
                'id': response[1].id,
            }
        return redirect('travel:dashboard')
    return redirect('travel:main')

def logout(request):
    request.session.clear()
    return redirect('travel:main')

apps/travel/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from ..LogReg.models import userDB
from .models import Trip

#displays main page with log and reg
def main(request):
    return render(request, 'travel/main.html')

#displays travel dashboard page
def dashboard(request):
    user = userDB.objects.get(id=request.session['user']['id'])
    context = {
        'trips': Trip.objects.filter(travelers=user),
        'other_trips': Trip.objects.all().exclude(travelers=user)
    }
    return render(request, 'travel/dashboard.html', context)

#adds other trip to user's trip
def join(request, id):
    user = userDB.objects.get(id=request.session['user']['id'])
    trip = Trip.objects.get(id=id)
    trip.travelers.add(user)
    trip.save()
    return redirect('travel:dashboard')

#displays destination page
def destination(request, id):
    context = {
        'trip': Trip.objects.get(id=id),
        'travelers': userDB.objects.filter(trip_travelers__id=id)
    }
    print context['trip'].travel_start_date
    return render(request, 'travel/destination.html', context)

#displays add page
def add_page(request):
    return render(request, 'travel/add.html')

#adds trip to user's trips
def add(request):
    if request.method == "POST":
        print request.POST['travel_start_date']
        user = userDB.objects.get(id=request.session['user']['id'])
        response = Trip.objects.check_trip(request.POST, user)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
            return redirect('travel:add_page')
    return redirect('travel:dashboard')

# Create your views here.

apps/LogReg/templates/LogReg/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <a href="{% url 'logreg:logout' %}">Logout</a>
  </body>
</html>

apps/LogReg/templates/LogReg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
  </head>
  <body>
    <main>
      {% if messages %}
      {% for message in messages %}
      <p>{{message}}</p>
      {% endfor%}
      {% endif %}
      <section>
        <form action="{% url 'logreg:register' %}" method="post">
          {% csrf_token %}
          <input type="text" name="first_name" placeholder="First Name">
          <input type="text" name="last_name" placeholder="Last Name">
          <input type="email" name="email" placeholder="Something@thisplace.com">
          <input type="password" name="password" placeholder="Password ********">
          <input type="password" name="confirmpass" placeholder="Confirm Password">
          <button type="submit" name="attempt" value="register">Register</button>
        </form>
      </section>
      <section>
        <form action="{% url 'logreg:login' %}" method="post">
          {% csrf_token %}
          <input type="email" name="email" placeholder="Something@thisplace.com">
          <input type="password" name="password" placeholder="Password ********">
          <button type="submit" name="attempt" value="login" class='btn'>Login</button>
        </form>
      </section>
    </main>
  </body>
</html>

apps/travel/templates/travel/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Plan</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'travel/css/style.css' %}">
  </head>
  <body>
    <nav>
      <a href="{% url 'travel:dashboard' %}">Home</a>
      <a href="{% url 'logreg:logout' %}">Log out</a>
    </nav>
    <h2>Add a Trip</h2>
    <div id="flash_messages">
      {% if messages %}
      {% for message in messages %}
      <p class="error">{{message}}</p>
      {% endfor %}
      {% endif %}
    </div>
    <form action="{% url 'travel:add' %}" method="post">
      {% csrf_token %}
      <p>Destination</p>
      <input type="text" name="destination">
      <p>Description</p>
      <input type="text" name="plan">
      <p>Travel Date From</p>
      <input type="date" name="travel_start_date">
      <p>Travel Date To</p>
      <input type="date" name="travel_end_date">
      <button type="submit" name="button">Add</button>
    </form>
  </body>
</html>

apps/travel/templates/travel/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Travel Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'travel/css/style.css' %}">
  </head>
  <body>
    <nav>
      <a href="{% url 'logreg:logout' %}">Log out</a>
    </nav>
    <h1>Hello,  {{request.session.user.username}}</h1>
    <h3>Your Trip Schedules</h3>
    <table>
      <thead>
        <th>Destination</th>
        <th>Travel Start Date</th>
        <th>Travel End Date</th>
        <th>Plan</th>
      </thead>
      <tbody>
        {% for trip in trips %}
        <tr>
          <td><a href="{% url 'travel:destination' trip.id %}">{{trip.destination}}</a></td>
          <td>{{trip.travel_start_date|date:"M d, Y"}}</td>
          <td>{{trip.travel_end_date|date:"M d, Y"}}</td>
          <td>{{trip.plan}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <h3>Other User's Travel Plans</h3>
    <table>
      <thead>
        <th>Name</th>
        <th>Destination</th>
        <th>Travel Start Date</th>
        <th>Travel End Date</th>
        <th>Do You Want to Join?</th>
      </thead>
      <tbody>
        {% for trip in other_trips %}
        <tr>
          <td>{{trip.planner.name}}</td>
          <td><a href="{% url 'travel:destination' trip.id %}">{{trip.destination}}</a></td>
          <td>{{trip.travel_start_date|date:"M d, Y"}}</td>
          <td>{{trip.travel_end_date|date:"M d, Y"}}</td>
          <td><a href="{% url 'travel:join' trip.id %}">Join</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'travel:add_page' %}">Add Travel Plan</a>
  </body>
</html>

apps/travel/templates/travel/destination.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Destination</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'travel/css/style.css' %}">
  </head>
  <body>
    <nav>
      <a href="{% url 'travel:dashboard' %}">Home</a>
      <a href="{% url 'logreg:logout' %}">Log out</a>
    </nav>
    <h1>{{trip.destination}}</h1>
    <p>Planned by: {{trip.planner.name}}</p>
    <p>Description: {{trip.plan}}</p>
    <p>Travel Date From: {{trip.travel_start_date|date:"M d, Y"}}</p>
    <p>Travel Date To: {{trip.travel_end_date|date:"M d, Y"}}</p>

    <h2>Other user's joining the trip:</h2>
    <ul>
      {% for traveler in travelers %}
      {% if traveler.username != trip.planner.username %}
      <li>{{traveler.name}}</li>
      {% endif %}
      {% endfor %}
    </ul>
  </body>
</html>

apps/travel/templates/travel/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'travel/css/style.css' %}">
  </head>
  <body>
    <h1>Welcome to Travel Buddy</h1>
    <div id="flash_messages">
      {% if messages %}
      {% for message in messages %}
      <p class="error">{{message}}</p>
      {% endfor %}
      {% endif %}
    </div>
    <div id="register">
      <h2>Register</h2>
        <form action="{% url 'logreg:register' %}" method="post">
          {% csrf_token %}
          <input type="text" name="name" placeholder="Name">
          <input type="text" name="username" placeholder="Username">
          <p>Password must be at least 8 characters.</p>
          <input type="password" name="password" placeholder="password ********">
          <input type="password" name="password_confirmation" placeholder="password confirmation">
          <button  type="submit" name="attempt" value="register">Register</button>
        </form>
    </div>
    <div id="login">
      <h2>Login</h2>
      <form action="{% url 'logreg:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username">
        <input type="password" name="password" placeholder="password *********">
        <button type="submit" name='attempt' value='login'>Log In</button>
      </form>
    </div>
  </body>
</html>